#!/bin/bash
DUPLY=$(dirname "$0")/duply.sh
#DUPLY=~jamoke/release/duply_1.5.2.3/duply
PATH=~/duplicity.gpginterface/trunk/bin:$PATH
#~jamoke/_apps/duplicity-0.6.19.tmp/bin:$PATH
# protect params with spaces, use "$@" instead
#for ((a=1; a <= ${#@}; a++)); do eval ARG="\${${a}}"; ARGS="$ARGS \"$ARG\""; done;
"$DUPLY" "$@" 

